version: "3.7"

services:
  api:
    image: ghcr.io/veryeasycode/edc-api:${EDC_API_VERSION:-latest}
    restart: always
    ports:
      - 30004:80
    networks:
      - site_ingress
    environment:
      PORT: 80
      MONGO_USERNAME: root
      MONGO_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_HOST: primary
      MONGO_PORT: 27017
      MONGO_DB: ${MONGODB_DB}
      MONGO_AUTH_DB: admin
      MONGO_REPLICA_SET: replicaset

  ui:
    image: ghcr.io/veryeasycode/edc-ui:${EDC_UI_VERSION:-latest}
    restart: always
    ports:
      - 30005:80
    networks:
      - site_ingress

networks:
  site_ingress:
    name: site_ingress
    external: true
