version: "3.7"

services:
  primary:
    image: "bitnami/mongodb:4.4.15"
    restart: always
    ports:
      - "27017:27017"
    networks:
      - site_ingress
    environment:
      MONGODB_ADVERTISED_HOSTNAME: primary
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_REPLICA_SET_KEY: ${MONGODB_REPLICA_SET_KEY}
    volumes:
      - "./data/mongo_primary:/bitnami/mongodb"

networks:
  site_ingress:
    name: site_ingress
    external: true
