version: '3.7'
services:
  avahi:
    image: ghcr.io/veryeasycode/bizarre-infrastructure/avahi:${AVAHI_VERSION:-latest}
    restart: always
    environment:
      REFLECTOR_ENABLE_REFLECTOR: "yes"
      SERVER_HOST_NAME: "${HOST_NAME:-local}" # Change this line following site name
      SERVER_ALLOW_INTERFACES: "" # Change this line if site use other interface
    network_mode: "host"

networks:
  site_ingress:
    name: site_ingress
    external: true
